name: "My test action"
description: "want to see if i can fire a repository dispatch"
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'doesNotReallyMatter'

runs:
  using: "composite"
  steps:
    - name: my_action_triggered_by_a_repository_dispatch
      shell: bash
      run: |
        echo "ok, i got triggered. do i get the input? ${{ inputs.who-to-greet }}"
