name: my_action_triggered_by_a_repository_dispatch

on:
  repository_dispatch:
    types:
      - deploy-service

jobs:
  trigger:
    name: my_action_triggered_by_a_repository_dispatch
    runs-on: ubuntu-latest
    steps:
      - name: my_action_triggered_by_a_repository_dispatch
        run: |
          echo "ok, i got triggered. do i get the input? ${{ inputs.who-to-greet }}"
